# Generated by Django 3.2.9 on 2021-12-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_period_subject_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
