# Generated by Django 3.2.9 on 2021-12-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_topic_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=259, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
