# Generated by Django 3.2.9 on 2021-12-11 17:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211208_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
